### ISSUE TITLE
Missing routes from the Lipas REST API

### ISSUE THREAD

**Issue by lauri-n** [lipas-liikuntapaikat/lipas-api#1]
Should all the same sports places that are visible on the Lipas map at https://www.lipas.fi/liikuntapaikat be also available through the REST API http://lipas.cc.jyu.fi/api?

I've come across quite a few trails especially that I can find on the map but can't get through the API.

Some examples:
Päijätsalon ulkoilureitti - 526047
Herajärven kierros - 600382
Raittijärven polku - 526471
Nuolivaaran luontopolku - 528638

If I try to get these with the "GET /sports-places/{sports-place-id}" request the response is 404.
Also trying to seach them with "GET /sports-places" and a searchString containing the name like http://lipas.cc.jyu.fi/api/sports-places?fields=name&searchString=Nuolivaaran doesn't produce any results.

Is this by design and if so are these and other items missing from this API available through some other API?

**Comment by vharmain** [comment]
Hi, the dataset should be the same between lipas.fi webapp and the REST-API. If some entries are missing from the API that's a mistake in our end. The data between the web-app and the API is synced every night. They are currently not using the same database for legacy reasons... I will check tonight/tomorrow why those entries are missing from the API and re-sync. Thanks for reporting!

**Comment by vharmain** [comment]
@lauri-n I just re-indexed all the data on the API side and now 526047, 600382, 526471, 528638 can be found also from the API. There was a problem with the nightly script due to recent server change.

Sorry for the trouble and thanks again for reporting! Please verify that this works now and then I'll close the issue.

**Comment by lauri-n** [comment]
These are working now, thanks!
