### ISSUE TITLE
GET /sports-place-types returning server error again

### ISSUE THREAD

**Issue by lauri-n** [lipas-liikuntapaikat/lipas-api#4]
The GET /sports-place-types has broken down again and is returning 500. This seems the same as #2 

Also the swagger.json is now showing the path of this method as `/api//sports-place-types` which does work normally.

Could be worth having even a simple set of automated tests for the API that are run after each deployment and nightly sync. Many of the recent issues would be quite easy to catch with such tests. Just an idea  ;)

**Comment by vharmain** [comment]
🤦‍♂️ Funny thing is that we _do_ have quite extensive tests but I was too lazy to run them... This is screaming for CI/CD... Perhaps during the summer-holidays I'll take the time.

This is fixed now. Sorry for the hassle and thanks again for reporting.

**Comment by vharmain** [comment]
Closing.
