### ISSUE TITLE
GET /sports-place-types returning server error

### ISSUE THREAD

**Issue by vloy** [lipas-liikuntapaikat/lipas-api#6]
The GET /api/sports-place-types is returning server error 500.

**Comment by vharmain** [comment]
This is now fixed. The issue was related to bad metadata when we added a few new type-codes. 

Sorry for the trouble and thanks for reporting!

**Comment by vloy** [comment]
Thank you!
Listing works now, but some single places still returns 500.
For example 2150 "liikuntasali", http://lipas.cc.jyu.fi/api/sports-place-types/2150?lang=fi

**Comment by vharmain** [comment]
@vloy this should also be fixed now!
